universe = Docker
docker_image = biocontainers/bowtie
requirements = (Target.HasCHTCStaging==TRUE)
arguments = "$(REF) $(RUN)"
executable = bowtie.sh

output = bowtie_$(RUN).out
error = bowtie_$(RUN).err
log = bowtie_$(RUN).log

# Rules to transfer and transferring files
transfer_executable = TRUE
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

staging_prefix = file:///staging/groups/pepperell_group/Mtb_RNAseq
results_staging_prefix = file:///staging/groups/pepperell_group/Mtb_RNAseq/Results
transfer_input_files = bowtie.sh, $(results_staging_prefix)/$(RUN)_1P.fq.gz, $(results_staging_prefix)/$(RUN)_2P.fq.gz, $(staging_prefix)/$(REF)
transfer_output_files = $(RUN)_bowtie_out.tar.gz
transfer_output_remaps = "$(RUN)_bowtie_out.tar.gz = $(results_staging_prefix)/$(RUN)_bowtie_out.tar.gz"

# Resource request and Queue job
requirements = (Target.HasCHTCStaging==TRUE)
request_cpus = 8
request_memory = 50GB 
request_disk = 60GB

queue